project_id = "rsahtxjpisnldxnsmupk"

[functions.get-mapbox-token]
verify_jwt = false

[functions.email-hook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true
